receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: 
    send_batch_max_size: 200
    send_batch_size: 200
    timeout: 5s
  memory_limiter:
    check_interval: 1s
    limit_percentage: 65
    spike_limit_percentage: 20
  resourcedetection:
    detectors: [env, gcp]
    timeout: 2s
    override: false
  resource:
    attributes:
    - key: service.instance.id
      from_attribute: faas.id
      action: upsert
    - key: service.name
      value: $${env:K_SERVICE}
      action: insert

exporters:
  googlemanagedprometheus:
  googlecloud:
    log:
      default_log_name: wasmcloud

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors:
        - batch
        - memory_limiter
        - resourcedetection
        - resource
      exporters: [googlecloud]
    metrics:
      receivers: [otlp]
      processors:
        - batch
        - memory_limiter
        - resourcedetection
        - resource
      exporters: [googlemanagedprometheus]


