style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/Mattilsynet/map-tf-wasmcloud-cr
options:
  sort: "semver"
  commits:
  commit_groups:
    title_maps:
      chore: Other Changes
      feat: Features
      fix: Bug Fixes
      refactor: Code Refactoring
      major: "**Breaking Changes**"
      breaking: "**Breaking Changes**"
      break: "**Breaking Changes**"
      doc: Documentation
      docs: Documentation
      fix!: "**Breaking Changes**"
      feat!: "**Breaking Changes**"
      feature!: "**Breaking Changes**"

  header:
    pattern: "^(\\w*!?)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?!?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGES
      - IMPORTANT
      - WARNING
